services:
  # GPU Version / GPU 版本
  whisper-stt:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
    image: whisper-stt:latest
    container_name: whisper-stt
    restart: always
    ports:
      - "5012:8000"
    env_file:
      - .env
    # environment 中的值会覆盖 .env（用于必须固定的值）
    environment:
      - WHISPER_CACHE_DIR=/root/.cache/huggingface/hub
    #  - ALIGNMENT_AUTO_DETECT_LANGUAGE=true  # Auto-detect language for alignment / 对齐启用自动语音检测
    volumes:
      - ./whisper-models:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # Use first GPU / 使用第一块 GPU
              capabilities: [gpu]
